#!/bin/sh

# shell utils
source $HOME/.config/bspwm/utils.sh

feh --bg-fill $HOME/Pictures/arch.png

# Executable, background flag, parameters, signal to send
exec_once_or_signal sxhkd 0 "" -USR1
exec_once_or_signal conky 1
exec_once_or_signal flameshot 0
exec_once_or_signal copyq 0
exec_once_or_signal safeeyes 0
exec_once_or_signal udiskie 0 "-t"

# Desktop specifics
if [ "$MACHINE_ENV" == "desktop" ]
then
        $HOME/.screenlayout/bspwm.sh
        bspc monitor HDMI-A-0 -d 1 3
        bspc monitor DisplayPort-0 -d 2 4
fi

# Laptop specifics
if [ "$MACHINE_ENV" == "laptop" ]
then
        # 
        bspc monitor -d 1 2 3 4 5
        clipmenud &
fi

# Start polybar after setting workspaces
polybar.sh &

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^5'
bspc rule -a copyq follow=on state=floating
bspc rule -a Chromium desktop='^2'
bspc rule -a Insomnia desktop='^4'
bspc rule -a Google-chrome desktop='^2'
