force_keyboard_focus = true
close_when_open = true
click_to_close = true
as_window = false
single_click_activation = true
selection_wrap = true
theme = "default"
hide_quick_activation = false
hide_action_hints = false

[shell]
exclusive_zone = -1
layer = "overlay"
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[placeholders]
"default" = { input = "Search apps or calculate…", list = "No results" }

[keybinds]
close     = ["Escape"]
next      = ["Down", "Tab", "ctrl n"]
previous  = ["Up", "shift Tab", "ctrl p"]
quick_activate = [
  "ctrl 1", "ctrl 2", "ctrl 3", "ctrl 4"
]

[providers]
default   = ["desktopapplications", "windows", "calc"]
empty     = ["desktopapplications"]
max_results = 10

[providers.max_results_provider]
calc = 1

[[providers.prefixes]]
prefix   = "="
provider = "calc"

[[providers.prefixes]]
prefix   = ">"
provider = "runner"

[[providers.prefixes]]
prefix   = ":"
provider = "clipboard"

[[providers.prefixes]]
prefix   = "/"
provider = "files"

[[providers.websearch]]
prefix   = "?"
provider = "websearch"

[providers.actions]
desktopapplications = [
  { action = "start",        default = true, bind = "Return" },
  { action = "new_instance", label = "new instance", bind = "ctrl Return" },
  { action = "pin", bind = "ctrl t", after = "AsyncReload" },
  { action = "unpin", bind = "ctrl t", after = "AsyncReload" },
  { action = "pinup", bind = "ctrl u", after = "AsyncReload" },
  { action = "pindown", bind = "ctrl d", after = "AsyncReload" },
]

calc = [
  { action = "copy",   default = true, bind = "Return" },
  { action = "delete", bind = "ctrl d", after = "AsyncReload" },
]

runner = [
  { action = "run",         default = true, bind = "Return" },
  { action = "runterminal", label = "in terminal", bind = "shift Return" },
]
