general {
    hide_cursor         = true
    grace               = 5
    no_fade_in          = false
    disable_loading_bar = false
}

background {
    monitor     =
    path        = screenshot
    blur_passes = 3
    blur_size   = 7
    brightness  = 0.6
}

input-field {
    monitor           =
    size              = 280, 52
    outline_thickness = 2
    dots_size         = 0.2
    dots_spacing      = 0.2
    dots_center       = true
    outer_color       = rgba(203, 166, 247, 0)
    inner_color       = rgba(30, 30, 46, 0.8)
    font_color        = rgb(205, 214, 244)
    fade_on_empty     = false
    placeholder_text  = <i>Password</i>
    check_color       = rgb(250, 179, 135)
    fail_color        = rgb(243, 139, 168)
    fail_text         = <i>$FAIL ($ATTEMPTS)</i>
    capslock_color    = rgb(249, 226, 175)
    position          = 0, -80
    halign            = center
    valign            = center
}

label {
    monitor     =
    text        = $TIME
    color       = rgba(205, 214, 244, 1.0)
    font_size   = 72
    font_family = monospace
    position    = 0, 160
    halign      = center
    valign      = center
}

label {
    monitor     =
    text        = $LAYOUT
    color       = rgba(186, 194, 222, 0.8)
    font_size   = 14
    font_family = monospace
    position    = 0, -140
    halign      = center
    valign      = center
}
