preload = ~/Pictures/wallpapers/wall_eDP-1.jpg
preload = ~/Pictures/wallpapers/wall_DP-1.jpg
preload = ~/Pictures/wallpapers/wall_DP-4.jpg

wallpaper {
	monitor = eDP-1
	path = ~/Pictures/wallpapers/wall_eDP-1.jpg
	fit_mode = cover
}

wallpaper {
	monitor = DP-1
	path = ~/Pictures/wallpapers/wall_DP-1.jpg
	fit_mode = cover
}

wallpaper {
	monitor = DP-3
	path = ~/Pictures/wallpapers/wall_DP-4.jpg
	fit_mode = cover
}

splash = false
ipc = off
