# hyprlock — Monokai

general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
    no_fade_in = false
}

background {
    monitor =
    color = rgba(272822ff)
}

input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.4
    outer_color = rgba(a6e22eff)
    inner_color = rgba(49483eff)
    font_color = rgba(f8f8f2ff)
    fade_on_empty = false
    placeholder_text = <span foreground="##f8f8f2"><i>password…</i></span>
    hide_input = false
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(a6e22eff)
    font_size = 96
    font_family = SF Mono
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d %B %Y")"
    color = rgba(f8f8f2ff)
    font_size = 18
    font_family = SF Mono
    position = 0, 0
    halign = center
    valign = center
}
