# Manuel
set -g prefix C-a
unbind C-b
bind C-a send-prefix

unbind l

bind b new-window
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind-key -r -T prefix h select-pane -L
bind-key -r -T prefix j select-pane -D
bind-key -r -T prefix k select-pane -U
bind-key -r -T prefix l select-pane -R

bind-key -r -T prefix M-h resize-pane -L 5
bind-key -r -T prefix M-j resize-pane -D 5
bind-key -r -T prefix M-k resize-pane -U 5
bind-key -r -T prefix M-l resize-pane -R 5

set-option -g status-bg colour235
set-option -g status-fg colour27
set -g mouse on
set -g set-titles on
set -g status on
set -g base-index 1
set -g pane-base-index 1
set -g focus-events on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
#set -g @plugin 'jimeh/tmux-themepack'
#set -g @themepack 'powerline/default/cyan'
set -g @plugin 'egel/tmux-gruvbox'
#set -g @plugin "arcticicestudio/nord-tmux"
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
