conky.config={
        alignment='bl',
        background=true,
        border_inner_margin=5,
        border_outer_margin=5,
        border_width=2,
        default_bar_height=5,
        default_bar_width=80,
        default_color="C0C0C0",
        default_graph_height=25,
        default_graph_width=200,
        default_outline_color="000000",
        default_shade_color="000000",
        double_buffer=true,
        draw_borders=false,
        draw_graph_borders=false,
        draw_outline=false,
        draw_shades=false,
        font="SF Mono:size=12",
        maximum_width=500,
        minimum_width=300,
        no_buffers=true,
        override_utf8_locale=true,
        own_window_class="conky",
        own_window_hints="undecorated,below,skip_taskbar,skip_pager,sticky",
        own_window_transparent=false,
        own_window_argb_visual=true,
        own_window_argb_value=156,
        own_window=true,
        own_window_type="override",
        stippled_borders=0,
        text_buffer_size=6144,
        total_run_times=0,
        update_interval=5,
        uppercase=false,
        use_spacer="none",
        use_xft=true,
        xftalpha=0.8,
        gap_x=5,
};

conky.text=[[
${font San Francisco Display:style=Bold:pixelsize=14}Tasks ${hr 2}${font}
${font :style=Bold:pixelsize=12}${texeci 60 task rc.report.simple}
]]
