[theme]

# Gruvbox Dark
background = "#282828"
primary = "light white"
secondary = "light black"
title = "cyan"
playing = "cyan"
playing_bg = "black"
highlight = "light white"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "cyan"
statusbar_progress = "black"
statusbar_bg = "#484848"
cmdline = "light white"
cmdline_bg = "black"
# Gruvbox Dark End
