# -*- conf -*-
# foot — Monokai

font=SF Mono Powerline:size=12
pad=8x8 center
dpi-aware=no

[mouse]
hide-when-typing=yes

[cursor]
style=block
blink=no
color=272822 f8f8f0

[colors]
alpha=1.0
background=272822
foreground=f8f8f2
selection-foreground=f8f8f2
selection-background=49483e

# Normal (0–7)
regular0=272822
regular1=f92672
regular2=a6e22e
regular3=f4bf75
regular4=66d9ef
regular5=ae81ff
regular6=a1efe4
regular7=f8f8f2

# Bright (8–15)
bright0=75715e
bright1=f92672
bright2=a6e22e
bright3=f4bf75
bright4=66d9ef
bright5=ae81ff
bright6=a1efe4
bright7=f9f8f5

# Misc
urls=66d9ef
jump-labels=272822 a6e22e
search-box-no-match=272822 f92672
search-box-match=272822 a6e22e
scrollback-indicator=272822 66d9ef

[csd]
preferred=none

# vim: ft=dosini
